services:
    db:
      container_name : postgres
      image: postgres
      restart: always
      environment:
        POSTGRES_PASSWORD: 1234
      healthcheck:
        test: ["CMD-SHELL", "pg_isready"]
        interval: 1s
        timeout: 5s
        retries: 10
  ## DJANGO BACKEND
  ## NGINX
  ## DEVOPS (GRAFANA, PROMETHEUS, PORTAINER)
